language: c
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
before_install:
    - cd ${HOME}
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - wget https://package-data.enthought.com/edm/rh6_x86_64/2.1/edm_cli_2.1.0_linux_x86_64.sh && bash ./edm_cli_2.1.0_linux_x86_64.sh -b -f -p $HOME
    - export PATH=${HOME}/edm/bin:${PATH}
    - cp edm.yaml $HOME/.edm.yaml
    - edm install -y click setuptools
    - cd ${HOME}/build/force-h2020/
    - git clone -b master git://github.com/force-h2020/force-bdss.git
    - pushd force-bdss && edm run -- python -m ci build-env && edm run -- python -m ci install && popd
    - cd force-bdss-plugin-granta-example
    - edm run -- python -m ci install-dummy-granta
script:
    - edm run -- python -m ci install
    - edm run -- python -m ci flake8
    - edm run -- python -m ci test
    - edm run -- python -m ci docs
after_success:
    - edm run -- python -m ci coverage
    - edm run -- pip install codecov
    - edm run -- codecov
    - bash <(curl -s https://codecov.io/bash)
