language: c
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - wget https://package-data.enthought.com/edm/rh5_x86_64/1.9/edm_1.9.2_linux_x86_64.sh && bash ./edm_1.9.2_linux_x86_64.sh -b -f -p $HOME
    - export PATH=${HOME}/edm/bin:${PATH}
    - cp edm.yaml $HOME/.edm.yaml
    - edm install -y click setuptools
    - git clone -b master git://github.com/force-h2020/force-bdss.git
    - pushd force-bdss && edm run -- python -m ci build-env
    - edm run -- python -m ci install-dummy-granta
script:
    - edm run -- python -m ci install
    - edm run -- python -m ci flake8
    - edm run -- python -m ci test
    - edm run -- python -m ci docs
after_success:
    - edm run -- python -m ci coverage
    - edm run -- pip install codecov
    - edm run -- codecov
    - bash <(curl -s https://codecov.io/bash)
